#############################################################################
# Makefile for building: build/http-req
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Aug 28 23:21:47 2025
# Project:  http-req.pro
# Template: app
# Command: /opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake -spec /opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/linux-g++-maemo CONFIG+=debug QMAKE_CXX=/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/g++ QMAKE_CC=/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/gcc -o Makefile http-req.pro
#############################################################################

####### Compiler, tools and options

CC            = /opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/gcc
CXX           = /opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/g++
DEFINES       = -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/linux-g++-maemo -I. -I/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -I/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtNetwork -I/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -I/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDeclarative -I/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Iqmlapplicationviewer -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -lQtDeclarative -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/networkmanager.cpp \
		src/buttonmanager.cpp \
		src/responseviewer.cpp \
		src/recentfiles.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_networkmanager.cpp \
		moc_buttonmanager.cpp \
		moc_responseviewer.cpp \
		moc_recentfiles.cpp \
		moc_qmlapplicationviewer.cpp
OBJECTS       = main.o \
		networkmanager.o \
		buttonmanager.o \
		responseviewer.o \
		recentfiles.o \
		qmlapplicationviewer.o \
		moc_networkmanager.o \
		moc_buttonmanager.o \
		moc_responseviewer.o \
		moc_recentfiles.o \
		moc_qmlapplicationviewer.o
DIST          = /opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/debug.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		http-req.pro
QMAKE_TARGET  = http-req
DESTDIR       = build/
TARGET        = build/http-req

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: http-req.pro  /opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/linux-g++-maemo/qmake.conf /opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/debug.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl \
		/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec /opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/linux-g++-maemo CONFIG+=debug QMAKE_CXX=/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/g++ QMAKE_CC=/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/gcc -o Makefile http-req.pro
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/debug.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl:
/opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/linux-g++-maemo CONFIG+=debug QMAKE_CXX=/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/g++ QMAKE_CC=/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/gcc -o Makefile http-req.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/http-req1.0.0 || $(MKDIR) .tmp/http-req1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/http-req1.0.0/ && $(COPY_FILE) --parents src/networkmanager.h src/buttonmanager.h src/responseviewer.h src/recentfiles.h qmlapplicationviewer/qmlapplicationviewer.h .tmp/http-req1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/networkmanager.cpp src/buttonmanager.cpp src/responseviewer.cpp src/recentfiles.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/http-req1.0.0/ && (cd `dirname .tmp/http-req1.0.0` && $(TAR) http-req1.0.0.tar http-req1.0.0 && $(COMPRESS) http-req1.0.0.tar) && $(MOVE) `dirname .tmp/http-req1.0.0`/http-req1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/http-req1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_networkmanager.cpp moc_buttonmanager.cpp moc_responseviewer.cpp moc_recentfiles.cpp moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_networkmanager.cpp moc_buttonmanager.cpp moc_responseviewer.cpp moc_recentfiles.cpp moc_qmlapplicationviewer.cpp
moc_networkmanager.cpp: src/networkmanager.h
	/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc $(DEFINES) $(INCPATH) src/networkmanager.h -o moc_networkmanager.cpp

moc_buttonmanager.cpp: src/recentfiles.h \
		src/buttonmanager.h
	/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc $(DEFINES) $(INCPATH) src/buttonmanager.h -o moc_buttonmanager.cpp

moc_responseviewer.cpp: src/recentfiles.h \
		src/responseviewer.h
	/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc $(DEFINES) $(INCPATH) src/responseviewer.h -o moc_responseviewer.cpp

moc_recentfiles.cpp: src/recentfiles.h
	/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc $(DEFINES) $(INCPATH) src/recentfiles.h -o moc_recentfiles.cpp

moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/opt/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/networkmanager.h \
		src/buttonmanager.h \
		src/recentfiles.h \
		src/responseviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

networkmanager.o: src/networkmanager.cpp src/networkmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networkmanager.o src/networkmanager.cpp

buttonmanager.o: src/buttonmanager.cpp src/buttonmanager.h \
		src/recentfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buttonmanager.o src/buttonmanager.cpp

responseviewer.o: src/responseviewer.cpp src/responseviewer.h \
		src/recentfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o responseviewer.o src/responseviewer.cpp

recentfiles.o: src/recentfiles.cpp src/recentfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recentfiles.o src/recentfiles.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_networkmanager.o: moc_networkmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networkmanager.o moc_networkmanager.cpp

moc_buttonmanager.o: moc_buttonmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buttonmanager.o moc_buttonmanager.cpp

moc_responseviewer.o: moc_responseviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_responseviewer.o moc_responseviewer.cpp

moc_recentfiles.o: moc_recentfiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recentfiles.o moc_recentfiles.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/http-req/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/http-req/qml/ 
	-$(INSTALL_DIR) /project/qml/http-req $(INSTALL_ROOT)/opt/http-req/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/http-req/qml/http-req
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/http-req/qml/ 


install_itemiconfolder: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/http-req//usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/opt/http-req//usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_DIR) /project/assets $(INSTALL_ROOT)/opt/http-req//usr/share/icons/hicolor/80x80/apps/


uninstall_itemiconfolder:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/http-req//usr/share/icons/hicolor/80x80/apps/assets
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/http-req//usr/share/icons/hicolor/80x80/apps/ 


install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /project/http-req_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/http-req_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/http-req/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/http-req/bin/ 
	-$(INSTALL_PROGRAM) "build/$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/http-req/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/http-req/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/http-req/bin/ 


install:  install_itemfolder_01 install_itemiconfolder install_desktopfile install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_itemiconfolder uninstall_desktopfile uninstall_target   FORCE

FORCE:

